/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-west-2",
    "aws_cognito_identity_pool_id": "us-west-2:b40938d0-b2c4-48eb-972a-868706cd56f1",
    "aws_cognito_region": "us-west-2",
    "aws_user_pools_id": "us-west-2_aHauGPGT3",
    "aws_user_pools_web_client_id": "2l5jf87ra31sncu6ge9s07p0me",
    "oauth": {},
    "aws_cognito_username_attributes": [],
    "aws_cognito_social_providers": [],
    "aws_cognito_signup_attributes": [
        "EMAIL"
    ],
    "aws_cognito_mfa_configuration": "OFF",
    "aws_cognito_mfa_types": [
        "SMS"
    ],
    "aws_cognito_password_protection_settings": {
        "passwordPolicyMinLength": 8,
        "passwordPolicyCharacters": []
    },
    "aws_cognito_verification_mechanisms": [
        "EMAIL"
    ],
    "aws_user_files_s3_bucket": "resumeparsers3storage112618-dev",
    "aws_user_files_s3_bucket_region": "us-west-2"
};


export default awsmobile;
